@startuml
skinparam classAttributeIconSize 0
skinparam packageStyle rectangle

package "US106 - Registar Aeroporto" {

    class AirportController <<RestController>> {
      + createAirport(airport: Airport): Airport
    }

    interface AirportRepository <<Repository>> {
      + existsById(id: String): boolean
      + save(airport: Airport): Airport
    }

    class Airport <<Entity>> {
      - iataCode: String
      - name: String
      - city: String
      - country: String
      - timezone: String
      - status: String
      + getIataCode(): String
    }

    AirportController "1" --> "1" AirportRepository : uses >
    AirportController ..> Airport : handles >
    AirportRepository ..> Airport : stores >
}
@enduml