@startuml
skinparam classAttributeIconSize 0
skinparam packageStyle rectangle

package "US106 - Registar Aeroporto" {

    class AirportController <<RestController>> {
      + createAirport(airport: Object): ResponseEntity
    }

    class RegisterAirportUseCase <<UseCase>> {
      + execute(): Airport
    }

    interface AirportRepository <<Repository>> {
      + existsById(iata: IataCode): boolean
      + save(airport: Airport): Airport
    }

    class Airport <<Aggregate Root>> {
      - name: String
      - city: String
      - country: String
      - timezone: String
      - status: String
      + Airport(iata: IataCode, name: String, city: String, country: String, timezone: String, status: String)
      + getIataCode(): IataCode
    }

    class IataCode <<Value Object>> {
      - code: String
      + IataCode(code: String)
      + getCode(): String
    }

    ' Relacionamentos
    AirportController "1" --> "1" RegisterAirportUseCase : delegates to >
    RegisterAirportUseCase "1" --> "1" AirportRepository : uses >

    RegisterAirportUseCase ..> Airport : creates >
    RegisterAirportUseCase ..> IataCode : creates >

    Airport "1" *-- "1" IataCode : identified by >
}
@enduml